site_name: yumy94me的个人博客
theme:
  name: material
  plaette:
    scheme: default
    primary: brown
    accent: amber

    # Palette toggle for light mode
    scheme: default
    toggle:
      icon: material/toggle-switch 
      name: Switch to dark mode

    # Palette toggle for dark mode
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode